
# https://www.gitpod.io/docs/references/gitpod-yml#ports

tasks:
  - name: jupyter
    # change working directory as per configured in `checkoutLocation`
    # which is configured above as `/workspaces/backend`
    # before: |
    #   cd ../backend
    # init: |
    #   echo npm install
    #   echo npm run build
    command: |
     ./start.sh

ports:
    # - name: Website
    #   port: 3000
    #   onOpen: open-preview
    - name: jupyter
      description: jupyter notebook
      port: 8888
      onOpen: open-browser
    # - name: Server
    #   port: 10000
    #   onOpen: ignore